# Generated by Django 6.0.4 on 2026-04-20 23:27

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('gender_probability', models.FloatField()),
                ('age', models.IntegerField()),
                ('age_group', models.CharField(choices=[('child', 'Child'), ('teenager', 'Teenager'), ('adult', 'Adult'), ('senior', 'Senior')], max_length=10)),
                ('country_id', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=100)),
                ('country_probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
