# Generated by Django 6.0.4 on 2026-04-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country_probability',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender_probability',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
