# Generated by Django 6.0.4 on 2026-04-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_country_probability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country_probability',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender_probability',
            field=models.FloatField(),
        ),
    ]
